/**
 * Utility Functions for Swtor Parser v2
 * @author Frank Schiemenz
 */
/*
* simple rounding function for n digits
*/
function round(x, n) {
  var a = Math.pow(10, n);
  return (Math.round(x * a) / a);
}
/*
* pre-upload checks
*/
function checkFileUpload() {
	
	var token = (document.form.file.value).split(".");
	
    switch(token[token.length - 1].toLowerCase()){
    	case "txt" : break;
    	case "zip" : break;
    	case ""	   : alert("Please choose a file."); break;
    	default    : alert("Extension not supported.");
    }
}
/*
* turns strings generated by php's json_encode() into js-arrays
* no looping tho!
*/
function json_decode(string) {

	var arr = new Array();
	var token = new Array();
	
	string = string.slice(1, token.length - 2);
	string = string.split(","); 

	for(var i=0; i<string.length; i++ )
	{
		token = string[i].split(":"); 
		arr[i] = new Array(token[0], parseFloat(token[1]));
	}
	
	return arr;	
}
